title: "Personal Webpage"
author: "SD"
baseurl: "/Sdsp-math"
url: "https://sdspmon.github.io"
javascript_enabled: true
plugins:
  - jekyll-relative-links
relative_links:
  enabled: true
  collections: true
markdown: kramdown
kramdown:
  input: GFM
  math_engine: mathjax
  mathjax: 
    cdn: https://cdnjs.cloudflare.com/ajax/libs/mathjax/2.7.7/MathJax.js?config=TeX-MML-AM_CHTML
collections:
  projects:
    output: true
    permalink: /projects/:name/
  talks:
    output: true
    permalink: /talks/:name/
# theme: minima
# minima:
#  include:
#    - /assets/css/custom.css
