theme: minima
minima:
  include:
    - /assets/css/custom.css
javascript_enabled: true
markdown: kramdown
kramdown:
  input: GFM
  math_engine: mathjax
  mathjax: 
    cdn: https://cdnjs.cloudflare.com/ajax/libs/mathjax/2.7.7/MathJax.js?config=TeX-MML-AM_CHTML
